// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/index.mdx?collection=docs"), "iac/getting-started.mdx": () => import("../content/iac/getting-started.mdx?collection=docs"), "iac/language.mdx": () => import("../content/iac/language.mdx?collection=docs"), "rpc/accounts.mdx": () => import("../content/rpc/accounts.mdx?collection=docs"), "rpc/admin.mdx": () => import("../content/rpc/admin.mdx?collection=docs"), "rpc/cheatcodes.mdx": () => import("../content/rpc/cheatcodes.mdx?collection=docs"), "rpc/network.mdx": () => import("../content/rpc/network.mdx?collection=docs"), "rpc/node.mdx": () => import("../content/rpc/node.mdx?collection=docs"), "rpc/overview.mdx": () => import("../content/rpc/overview.mdx?collection=docs"), "rpc/transactions.mdx": () => import("../content/rpc/transactions.mdx?collection=docs"), "rpc/websockets.mdx": () => import("../content/rpc/websockets.mdx?collection=docs"), "resources/video-tutorials.mdx": () => import("../content/resources/video-tutorials.mdx?collection=docs"), "toolchain/cli.mdx": () => import("../content/toolchain/cli.mdx?collection=docs"), "toolchain/getting-started.mdx": () => import("../content/toolchain/getting-started.mdx?collection=docs"), "toolchain/tui.mdx": () => import("../content/toolchain/tui.mdx?collection=docs"), "iac/svm/actions.mdx": () => import("../content/iac/svm/actions.mdx?collection=docs"), "iac/svm/functions.mdx": () => import("../content/iac/svm/functions.mdx?collection=docs"), "iac/svm/overview.mdx": () => import("../content/iac/svm/overview.mdx?collection=docs"), "iac/svm/signers.mdx": () => import("../content/iac/svm/signers.mdx?collection=docs"), "iac/std/actions.mdx": () => import("../content/iac/std/actions.mdx?collection=docs"), "iac/std/functions.mdx": () => import("../content/iac/std/functions.mdx?collection=docs"), "iac/std/overview.mdx": () => import("../content/iac/std/overview.mdx?collection=docs"), "iac/std/actions/http.mdx": () => import("../content/iac/std/actions/http.mdx?collection=docs"), "iac/std/functions/assertions.mdx": () => import("../content/iac/std/functions/assertions.mdx?collection=docs"), "iac/std/functions/base58.mdx": () => import("../content/iac/std/functions/base58.mdx?collection=docs"), "iac/std/functions/base64.mdx": () => import("../content/iac/std/functions/base64.mdx?collection=docs"), "iac/std/functions/crypto.mdx": () => import("../content/iac/std/functions/crypto.mdx?collection=docs"), "iac/std/functions/hash.mdx": () => import("../content/iac/std/functions/hash.mdx?collection=docs"), "iac/std/functions/hex.mdx": () => import("../content/iac/std/functions/hex.mdx?collection=docs"), "iac/std/functions/json.mdx": () => import("../content/iac/std/functions/json.mdx?collection=docs"), "iac/std/functions/list.mdx": () => import("../content/iac/std/functions/list.mdx?collection=docs"), "iac/std/functions/operators.mdx": () => import("../content/iac/std/functions/operators.mdx?collection=docs"), }),
};
export default browserCollections;